baseurl = "https://schemmy.github.io"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Now optimize what?"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "G-EZT231LZ7Z"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = ":)"
#  mainSections = ["post", "page"]
  mainSections = ["post"]
  logo = "img/f1.jpeg" # Expecting square dimensions
  favicon = "img/f1.ico"
  dateFormat = "January 2, 2006"
  commit = false
  #rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  #socialShare = true
  delayDisqus = false
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Chenxin Ma"
  website = "schemmy.github.io"
  #email = "cxmmwq |a| gmail.com"
  github = "schemmy"
  linkedin = "chenxin-ma-86076256"
  googlescholar = "jwL__QkAAAAJ&hl"

#[[menu.main]]
#    name = "Blog"
#    url = ""
#    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 4

[[menu.main]]
    identifier = "data_mining"
    name = "data mining"
    weight = 2

[[menu.main]]
    parent = "data_mining"
    name = "Research connections"
    url = "post/research_connections"
    weight = 1

[[menu.main]]
    parent = "data_mining"
    name = "sport fans"
    url = "post/sportfans"
    weight = 2


[[menu.main]]
    identifier = "optimization"
    name = "optimization"
    weight = 2


[[menu.main]]
    parent = "optimization"
    name = "symmetry of neural nets"
    url = "post/dnn_symmetry"
    weight = 1

[[menu.main]]
    identifier = "blog"
    name = "blog"
    weight = 3

[[menu.main]]
    parent = "blog"
    name = "cron job"
    url = "page/add_cron_jobs"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

